### ISSUE TITLE
Вероятно, неактуальный конфиг

### ISSUE THREAD

**Issue by karuna-heks** [ISGNeuroTeam/CoAuthor#4]
В 11й строке скрипта **context_gen.py** запрашивается файл "config_local.yaml", которого нет в репозитории, т.к. он в .gitignore, но есть файл config.yaml, который, видимо, неактуален, т.к. тоже возвращает ошибку.

**Comment by annachikina** [comment]
спасибо, это я протупила, действительно должен быть config.yaml. поправила
